CapitalData = {
	
		"uz": [
			{"🇺🇿 O'zbekiston" : "Toshkent"},
			{"🇳🇱 Niderlandiya" : "Amsterdam"},
			{"🇦🇩 Andorra" : "Andorra-la-Velya"},
			{"🇬🇷 Gretsiya" : "Afina"},
			{"🇷🇸 Serbiya" : "Belgrad"},
			{"🇩🇪 Germaniya" : "Berlin"},
			{"🇨🇭 Shveysariya" : "Bern"},
			{"🇸🇰 Slovakiya" : "Bratislava"},
			{"🇧🇪 Belgiya" : "Brussel"},
			{"🇭🇺 Vengriya" : "Budapesht"},
			{"🇷🇴 Ruminiya" : "Buxarest"},
			{"🇮🇪 Irlandiya" : "Dublin"},
			{"🇺🇦 Ukraina" : "Kiyev"},
			{"🇲🇩 Moldava" : "Kishinyov"},
			{"🇩🇰 Daniya" : "Kopengagen"},
			{"🇵🇹 Portugaliya" : "Lissabon"},
			{"🇬🇧 Buyuk Britaniya" : "London"},
			{"🇸🇮 Sloveniya" : "Lyublyana"},
			{"🇱🇺 Lyuksemburg" : "Lyuksemburg"},
			{"🇪🇸 Ispaniya" : "Madrid"},
			{"🇧🇾 Belarus" : "Minsk"},
			{"🇲🇨 Monako" : "Monako"},
			{"🇷🇺 Rossiya" : "Moskva"},
			{"🇳🇴 Norvegiya" : "Oslo"},
			{"🇫🇷 Fransiya" : "Parij"},
			{"🇨🇿 Chexiya" : "Praga"},
			{"🇮🇸 Islandiya" : "Reykyavik"},
			{"🇱🇻 Latviya" : "Roga"},
			{"🇮🇹 Italiya" : "Rim"},
			{"🇸🇲 San Marino" : "San-Marino"},
			{"🇧🇦 Bosniya va Gertsogovina" : "Sarayevo"},
			{"🇲🇰 Makedoniya" : "Skopye"},
			{"🇧🇬 Bolgraiya"	 : "Sofiya"},
			{"🇸🇪 Shvetsiya" : "Stokgolm"},
			{"🇪🇪 Estoniya" : "Tallin"},
			{"🇦🇱 Albaniya" : "Tirana"},
			{"🇱🇮 Lixtenshteyn" : "Vaduts"},
			{"🇲🇹 Malta" : "Valetta"},
			{"🇵🇱 Polsha" : "Varshava"},
			{"🇻🇦 Vatikan" : "Vatikan"},
			{"🇦🇹 Avstriya" : "Vena"},
			{"🇱🇹 Litva" : "Vilnyus"},
			{"🇫🇮 Finlandiya" : "Helsinki"},
			{"🇭🇷 Xorvatiya" : "Zagreb"},
			{"🇲🇪 Chernogoriya" : "Podgoritsa"},
			{"🇽🇰 Kosovo" : "Prishtina"},
			{"🇦🇪 Birlashgan Arab Amirliklari" : "Abu-Dabi"},
			{"🇯🇴 Iordaniya" : "Ummon"},
			{"🇹🇷 Turkiya" : "Anqara"},
			{"🇹🇲 Turkmaniston" : "Ashxobod"},
			{"🇮🇶 Iroq" : "Bag'dod"},
			{"🇦🇿 Ozarbayjon" : "Baku"},
			{"🇹🇭 Tailand" : "Bangkok"},
			{"🇧🇳 Bruney" : "Bandar-Seri-Begavan"},
			{"🇱🇧 Livan" : "Bayrut"},
			{"🇰🇬 Qirg'iziston" : "Bishkek"},
			{"🇱🇦 Laos" : "Ventyan"},
			{"🇧🇩 Bangladesh" : "Dakka"},
			{"🇸🇾 Suriya" : "Damashq"},
			{"🇮🇳 Hindiston" : "Nyu-Dehli"},
			{"🇮🇩 Indoneziya" : "Jakarta"},
			{"🇹🇱 Sharqiy Timor" : "Dili"},
			{"🇶🇦 Qatar" : "Doha"},
			{"🇹🇯 Tojikiston" : "Dushanbe"},
			{"🇦🇲 Armaniston" : "Yerevan"},
			{"🇮🇱 Isroil" : "Quddus"},
			{"🇵🇰 Pokiston" : "Islomobod"}, 
			{"🇦🇫 Afg'oniston" : "Qobul"},
			{"🇳🇪 Nepal" : "Katmandu"},
			{"🇲🇾 Malayziya" : "Kuala-Lampur"},
			{"🇲🇻 Maldiv" : "Male"},
			{"🇧🇭 Bahrayn" : "Manama"},
			{"🇵🇭 Filippin" : "Manila"},
			{"🇲🇲 Myanma" : "Neypido"},
			{"🇰🇮 Kipr" : "Nikosiya"},
			{"🇰🇿 Qozog'iston" : "Nur-Sulton"},
			{"🇨🇳 Xitoy" : "Pekin"},
			{"🇰🇭 Kambodja" : "Pnopen"},
			{"🇰🇷 Koreya Respublikasi" : "Seul"},
			{"🇾🇪 Yaman" : "Sano"},
			{"🇸🇬 Singapur" : "Singapur"},
			{"🇬🇪 Gruziya" : "Tbilisi"},
			{"🇮🇷 Eron" : "Tehron"},
			{"🇯🇵 Yaponiya" : "Tokio"},
			{"🇧🇹 Butan" : "Thimphu"},
			{"🇲🇳 Mongoliya" : "Ulan-Bator"},
			{"🇻🇳 Vyetnam" : "Xanoy"},
			{"🇱🇰 Shri-Lanka" : "Jayavardenepura-Kotte"},
			{"🇰🇼 Quvayt" : "Al-Quvayt"},
			{"🇸🇦 Saudiya Arabistoni" : "Ar-Riyod"},
			{"🇵🇸 Falastin" : "Ramalla"},
			{"🇹🇼 Tayvan Respublikasi" : "Taybey"},
			{"🇳🇬 Nigeriya" : "Abuja"},
			{"🇪🇹 Efiopiya" : "Addis-Abeba"},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			# {"" : ""},
			],

		"ru": [
			{"🇺🇿 Узбекистана" : "Ташкент"},
			{"" : ""},
			{"" : ""},
			{"" : ""},
			{"" : ""},
			{"" : ""},
			{"" : ""},
		]


	
	
}
import random


def QuizMaker(lang="uz",polls_count=4):
	choice = random.choice(CapitalData[lang])
	country = ""
	variants = []
	correct_answer = ""
	for x,y in choice.items():
		country = country + x
		correct_answer = correct_answer + y
		variants.append(correct_answer)

	flag = True
	while flag:
		choice = random.choice(CapitalData["uz"])
		for y in choice.values():
			if y in variants:
				pass
				
			else:
				variants.append(y)
		if len(variants) == polls_count:flag = False
	random.shuffle(variants)
	return {"country":country,"correct_answer":correct_answer,"variants":variants}
if __name__ == '__main__':
	print(QuizMaker(polls_count=5))
